from django.urls import path
from backend.views import *

urlpatterns = [
    path('register', api_register_auth , name='api_register_auth'),
    path('login', api_login_auth , name='api_login_auth'),
    path('logout', api_logout_auth , name='api_logout_auth'),
    path('update', api_update_auth , name='api_update_auth'),
    
    path('notifications', api_get_notification , name='api_get_notification'),
    path('seen_notification', api_seen_notification , name='api_seen_notification'),
    
    # TEACHER ------------------------
    path('create_classroom', api_create_classroom , name='api_create_classroom'),
    path('get_teacher_classrooms', api_get_teacher_classrooms , name='api_get_teacher_classroom'),
    path('update_classroom', api_update_teacher_classroom , name='api_update_teacher_classroom'),
    path('get_teacher_selected_classroom', api_get_teacher_classroom , name='api_get_teacher_classroom'),
    path('get_teacher_classroom_materials', api_get_teacher_materials , name='api_get_teacher_materials'),
    path('delete_classroom' , api_teacher_delete_classroom , name='api_teacher_delete_classroom'),
    path('create_material', api_teacher_add_material , name='api_teacher_add_material'),
    path('delete_material', api_teacher_delete_material , name='api_teacher_delete_material'),
    path('get_teacher_material', api_teacher_get_material , name='api_teacher_get_material'),
    path('update_material', api_teacher_update_material , name='api_teacher_update_material'),
    path('get_teacher_materials_joined', api_teacher_get_material_joined , name='api_teacher_get_material_joined'),
    path('get_teacher_classroom_post', api_teacher_get_post , name='api_teacher_get_post'),
    path('add_teacher_classroom_post', api_teacher_create_post , name='api_teacher_create_post'),
    path('delete_teacher_classroom_post', api_teacher_remove_post , name='api_teacher_remove_post'),
    path('get_teacher_classroom_selected_post', api_teacher_get_selected_post , name='api_teacher_get_selected_post'),
    path('reply_teacher_classroom_post', api_teacher_reply_post , name='api_teacher_reply_post'),
    path('get_teacher_classroom_post_replies', api_teacher_get_replies , name='api_teacher_get_replies'),
    path('delete_teacher_classroom_post_reply', api_teacher_delete_replies , name='api_teacher_delete_replies'),
    path('teacher_check_students', api_teacher_check_all_students , name='api_teacher_check_all_students'),
    path('teacher_check_student', api_teacher_check_student , name='api_teacher_check_student'),
    path('teacher_activities', api_get_teacher_activities , name='api_get_teacher_activities'),
    path('teacher_delete_activity', api_teacher_delete_activity , name='api_teacher_delete_activity'),
    path('teacher_add_activity', api_teacher_add_activity , name='api_teacher_add_activity'),
    path('teacher_get_activity', api_teacher_get_activity , name='api_teacher_get_activity'),
    path('teacher_get_activity_joined', api_teacher_get_activity_joined , name='api_teacher_get_activity_joined'),
    path('teacher_get_activity_files', api_teacher_get_activity_files , name='api_teacher_get_activity_files'),
    path('teacher_get_dashboard', api_teacher_get_dashboard , name='api_teacher_get_dashboard'),
    path('teacher_get_student_activity', api_teacher_get_student_activity , name='api_teacher_get_student_activity'),
    path('teacher_get_student_activity_files', api_teacher_get_student_activity_files , name='api_teacher_get_student_activity_files'),
    path('teacher_get_report', api_teacher_get_report , name='api_teacher_get_report'),
    path('teacher_check_student_activity', api_teacher_check_student_activity , name='api_teacher_check_student_activity'),
    
    # STUDENT ------------------------
    path('join_classroom', api_student_join_classroom , name='api_student_join_classroom'),
    path('get_student_classroom', api_get_student_classrooms , name='api_get_student_classroom'),
    path('visit_student_classroom', api_get_student_classroom , name='api_get_student_classroom'),
    path('get_student_activities_materials', api_get_student_materials_activities , name='api_get_student_materials'),
    path('leave_student_classroom', api_student_leave_classroom , name='api_student_leave_classroom'),
    path('get_student_classroom_materials', api_student_get_material , name='api_student_get_material'),
    path('update_student_material', api_student_join_material , name='api_student_join_material'),
    path('get_student_classroom_post', api_student_get_post , name='api_student_get_post'),
    path('reply_student_classroom_post', api_student_reply_post , name='api_student_reply_post'),
    path('get_student_classroom_selected_post', api_student_get_selected_post , name='api_student_get_selected_post'),
    path('get_student_classroom_post_replies', api_student_get_replies , name='api_student_get_replies'),
    path('student_get_dashboard', api_student_get_dashboard , name='api_student_get_dashboard'),
    path('student_get_activity', api_student_get_activity , name='api_student_get_activity'),
    path('student_get_activity_files', api_student_get_activity_files , name='api_student_get_activity_files'),
    path('student_submit_activity_files', api_student_submit_activity_files , name='api_student_submit_activity_files'),
    
    path('student_submit_checking_activity_files', api_student_submit_checking_activity_files , name='api_student_submit_checking_activity_files'),
]